export const navigationConstants = {
  service: 'service',
  contacts: 'contacts',
  signIn: 'signIn',
  support: 'support',
  supportStackNavigator: 'supportStackNavigator',
  lessonBooking: 'lessonBooking',
  lessonDeletion: 'lessonDeletion',
  lessonRemote: 'lessonRemote',
  account: 'account',
  studentStackNavigator: 'studentStackNavigator',
  student: 'student',
  lessonsSchedule: 'lessonsSchedule',
  pinboard: 'pinboard',
  report: 'report',
  hourCount: 'hourCount',
  activePackage: 'activePackage',
  warningNote: 'warningNote',
}
